routes/web.php
<?php

Route::get('/', 'PublicHomeController@index');
// Route::get('/', function () {
// 	//return Redirect::route('user-register.index');

//    // return view('public.home');
// });


Route::get('/check-me', function(){
	$captains =App\Captain::with('rates')->get();
  //App\Http\Resources\CaptainCollection::withoutWrapping();
	$data=new App\Http\Resources\CaptainCollection($captains);

	return $data;
});

Route::get('/custom_offer' ,'ScheduleController@custom_offer')->name('custom_offer');
Route::get('/weakly_offer' ,'ScheduleController@weakly_offer')->name('weakly_offer');
Route::get('/yearly_offer' ,'ScheduleController@yearly_offer')->name('yearly_offer');
Route::get('/monthly_offer' ,'ScheduleController@monthly_offer')->name('monthly_offer');
//////Admin Routes;
Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	

/////user Dashboard
Route::prefix('user')->group(function(){
 // Authentication Routes...
	Auth::routes();
	Route::get('/profile', 'User\UserResource@profile')->name('user.profile');
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::post('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::Resource('advance-booking','User\AdvanceBookingController');
	Route::Resource('good','User\GoodsController');
	Route::Resource('vehical','User\VehicalTypeController');
	Route::Resource('booking','User\BookingController');
	Route::Resource('Ride','User\RidesController');
	Route::get('pending-Ridess', 'User\RidesController@pendingride')->name('pending-Rides');
	Route::Resource('googlemap' ,'User\GoogleMapController');
	Route::Resource('userResources' ,'User\UserResource');
	Route::get('user-walletss/{id}', 'User\UserResource@walletShow');
	

});

Route::prefix('admin')->group(function(){

	Route::get('/giveme','Admin\RoleController@giveme');
	Route::get('/checkme','Admin\RoleController@checkme');

	////Accounts
	Route::resource('code','Admin\Account\AccountCodeController');
	Route::resource('bank-deposit','Admin\Account\BankDepositController');
	Route::resource('bank-payment','Admin\Account\BankPaymentController');
	Route::resource('cash-payment','Admin\Account\CashPaymentController');
	Route::resource('cash-reciept','Admin\Account\CashRecieptController');
	Route::resource('invoice','Admin\Account\InvoiceController');
	Route::resource('journal-voucher','Admin\Account\JvController');
	Route::resource('ledger','Admin\Account\LedgerController');
	Route::resource('financials','Admin\Account\FinancialController');
	Route::resource('payable','Admin\Account\PayableAccountController');
	Route::resource('receivable','Admin\Account\RecivableController');
	Route::get('/accounts/detail','Admin\Account\LedgerController@all_account_record')->name('code.all_account');
	Route::post('code/create','Admin\Account\AccountCodeController@create_form')->name('account.new_acc');
Route::post('code/get_account', 'Admin\Account\AccountCodeController@get_account')->name('get_account');
Route::post('recivable/reciveable_account_record','Admin\Account\RecivableController@reciveable_account_record')->name('reciveable_account_record');
Route::post('payable/payables_account_record','Admin\Account\PayableAccountController@payables_account_record')->name('payables_account_record');
Route::post('/ledger/ledger_detail', 'Admin\Account\LedgerController@ledger_detail')->name('ledger_detail');
Route::post('ledger/search/record','Admin\Account\LedgerController@search_ledger_amount')->name('search_ledger_amount');

	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	
	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

	Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::Resource('userResource' ,'UserResource');

	Route::get('/user/send','UserResource@send');
Route::get('delete_record/{id}' ,'UserResource@delete_record');
	Route::post('/user_data','UserResource@get_users')->name('get-data');
	Route::post('/user_status','UserResource@user_change_status')->name('user-change-status');

	Route::get('/booking-detail/{id}' ,'UserResource@bookingdetail')->name('booking-detail');
	Route::get('user-wallet/{id}', 'UserResource@walletShow')->name('user-wallet');

	Route::Resource('adminResource' ,'AdminResource');

	Route::post('/admin_data','AdminResource@get_admin')->name('get-admin');
	Route::post('/admin_status','AdminResource@admin_change_status')->name('admin-change-status');
Route::get('admin_delete_record/{id}' ,'AdminResource@delete_record');

	Route::Resource('captainResource' ,'CaptainResource');

	Route::post('/captain_account', 'CaptainResource@captain_account')->name('captain_account');

	Route::post('/captain_getsss','CaptainResource@get_captain')->name('get-captainss');
	Route::post('/change_status','CaptainResource@captain_change_status')->name('captain-change-status');
Route::get('captain/delete_record/{id}' ,'CaptainResource@delete_record');
	Route::get('captain-wallet/{id}', 'CaptainResource@walletShow')->name('captain-wallet');


	Route::Resource('goods' ,'GoodsController');
	Route::get('good_delete_record/{id}' ,'GoodsController@delete_record');
	Route::get('good/delete_record/{id}' ,'GoodsController@delete_record');
	Route::post('/get_good','GoodsController@get_good')->name('get-good');
	Route::post('/good_status','GoodsController@good_change_status')->name('good-change-status');

	Route::Resource('captain-wallet' ,'CaptainWalletController');
	Route::Resource('googlemaps' ,'GoogleMapController');
	Route::Resource('vehicals', 'VehicalTypeController');
	Route::get('vehicals/delete_record/{id}' ,'VehicalTypeController@delete_record');
	Route::post('/get_vehical','VehicalTypeController@get_vehical')->name('get_vehical');
	Route::post('/vehical_change_status','VehicalTypeController@vehical_change_status')->name('vehical-change-status');
	

	Route::Resource('bookings', 'BookingController');
	Route::post('/booking_data','BookingController@get_booking')->name('get-booking');

	Route::Resource('pending-booking', 'PendingBookingController');
	Route::post('/pending_booking_data','PendingBookingController@get_pendingbooking')->name('get-pending-booking');



	Route::Resource('advance-bookings', 'AdvanceBookingController');

	Route::Resource('Rides' , 'RidesController');
	Route::post('/ride-data','RidesController@get_ride')->name('get-ride');
	
	Route::get('pending-Rides', 'RidesController@pendingride')->name('pendingRide');
	Route::post('/pending_data','RidesController@get_pending')->name('get-pending');

	Route::post('/upload_document_file','CaptainResource@upload_document_file')->name('upload_document_file');
	Route::post('/remove_document_file','CaptainResource@remove_document_file')->name('remove_document_file');

	Route::get('search','CaptainResource@searchbar')->name('searching');
	Route::Resource('good-categories' , 'GoodCategoriesController');
	Route::post('/get_cat','GoodCategoriesController@get_cat')->name('get_cat');
	Route::post('/cat_status','GoodCategoriesController@categories_change_status')->name('cat-change-status');

	Route::Resource('vehicle-sub-categories' , 'VehicleSubCategoriesController');
	Route::get('vehicle_delete_record/{id}' ,'VehicleSubCategoriesController@delete_record');
	Route::post('/get_sub_vehical','VehicleSubCategoriesController@get_sub_vehical')->name('get_sub_vehical');
	Route::post('/vcategories_change','VehicleSubCategoriesController@vcategories_change_status')->name('vcategories_change_status');
	Route::get('vehicle_categoires', 'VehicleSubCategoriesController@select_vehicle_categories')->name('vehicle-categories_data');

	Route::Resource('vehical-categories' , 'VehicalCategoriesController');
		Route::get('vehicle_categories_delete_record/{id}' ,'VehicalCategoriesController@delete_record');
	Route::post('/get_cat_vehical','VehicalCategoriesController@get_cat_vehical')->name('get-cat-vehical');
	Route::post('/categories_change_status','VehicalCategoriesController@categories_change_status')->name('category-change-status');

	Route::resource('roles', 'RoleController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('financial', 'FinancialController');

	Route::get('report/{id}', 'CaptainReportController@report');
	Route::get('captain_report' ,'CaptainReportController@filtercaptain')->name('captain_report');
	
	Route::resource('report' , 'CaptainReportController');

	Route::get('/get-captains-ajax' ,'CaptainResource@get_captains_ajax');
	Route::resource('inflow' , 'TransactionController' );
	Route::post('/traction','TransactionController@tracking_datas')->name('transaction-history');
	Route::resource('/emergencies','EmergencyController');
	Route::get('emergency_delete_record/{id}' ,'EmergencyController@delete_record');
		Route::post('/get_emergencies','EmergencyController@get_emergnecies')->name('get-emergencies');
		Route::post('/emergencies_change_status','EmergencyController@emergnecies_change_status')->name('emergencies-change-status');


	Route::resource('/offers','OfferController');
	Route::get('offer_delete_record/{id}' ,'OfferController@delete_record');
		Route::post('/get_offer','OfferController@get_offers')->name('get-offer');
		Route::post('/offer_change_status','OfferController@offerschange_status')->name('offer-change-status');

	Route::Resource('skip-reasons' ,'SkipReasonController');

app/Http/Controllers/User/AdvanceBookingController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\AdvanceBooking;
use Illuminate\Support\Facades\Input;

class AdvanceBookingController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {
        $book = AdvanceBooking::orderBy('id', 'DESC')->with("user")->with("vehical")->with("good")->paginate(5);
       
        $books =AdvanceBooking::count();
        return view('user.advanceBooking' , compact([ 'book', 'books']));
    }
}

app/Http/Controllers/User/BookingController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use App\Booking;
use App\Ride;
use Illuminate\Support\Facades\Input;
use Auth;

class BookingController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    public function index()
    {
        $book = Booking::where('user_id', Auth::guard('web')->id())->orderBy('id', 'DESC')->with('BookingDestination')->with('user')->with('good')->paginate(10);
        $books =Booking::count();
        return view('user.bookings' , compact([ 'book', 'books']));
    }

    public function show($id)
    {
        $Booking = Booking::where('id', $id)->with('BookingDestination')->with('good')->with('user')->with('vehical')->get();
        $ride = Ride::where('booking_id' , $id)->with('captain')->with('RideCompleted')->get();
        //return $Booking;exit;
        //dd($ride);exit;
      return view('user.bookingDetail', compact('Booking', 'ride'));
    }
}

app/Http/Controllers/User/GoodsController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use App\Good;


class GoodsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {
        $datatype = Good::orderBy('id', 'DESC')->paginate(5);
       // $datatypes =goods::count();
       // $categoris =goods_categories::count();
        return view('user.goodstype', compact(['$datatype', 'datatype']));
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        Good::create([
            'good_name'          => $request['good_name'],
            'good_category_id'   => $request['good_category_id'],
            ]);
        return redirect('good');
    }

    
    public function show(datatype $datatype)
    {
        //
    }

    
    public function edit($id)
    {
         $Datatypes = Good::find($id);
    
        return view('user.goodstypeEdit', compact('Datatypes'));
        
    }

    
    public function update(Request $request, $id)
    {
        $Datatypes = Good::findOrFail($id);
        $input = $request->all();

        $Datatypes->update($input);
        return redirect()->route('good.index');
    }

   
    public function destroy($id)
    {
       $datatyp = Good::find($id);
    
     
       
        $datatyp->delete();
        return Redirect::route('good.index');
    }    
}

app/Http/Controllers/User/GoogleMapController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GoogleMapController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {   
        return view('user.maps_vector');
    }
   
}

app/Http/Controllers/User/RidesController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;
use App\Http\Controllers\Controller;
use App\Ride;
use App\RidesCompleted;
use Auth;

class RidesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth:web']);
    }
    
        public function index()
        {
            $ride = Ride::where('user_id' , Auth::guard('web')->id())->where('status', 0 )->with("user")->with("captain")->with("booking")->with('BookingDestination')->with("RideCompleted")->orderBy('id', 'DESC')->paginate(10);
            $rides =Ride::count();
            return view('user.rides' , compact([ 'ride', 'rides']));
        }

        public function pendingride()
        {
        $ride = Ride::where('user_id' , Auth::guard('web')->id())->where('status','<>',0)->with("user")->with("captain")->with("booking")->with("advancebookings")->paginate(10);
        $rides =Ride::count();
        return view('user.pendingrides' , compact([ 'ride', 'rides']));
        }

        public function show($id){
            $ride_complete = RidesCompleted::where('ride_id' ,$id)->with('BookingDestination')->first();
            return view('user.rideproof' , compact([ 'ride_complete']));
        }
}

app/Http/Controllers/User/VehicalTypeController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;


use App\Vehical;


class VehicalTypeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
     { 

        $vehicals = Vehical::orderBy('id', 'DESC')->paginate(5);
        //$vehicals =vehicals::count();
       
        return view('user.vehicaltype', compact(['vehicals']));


     }
    public function create()
    {
        
    }

    
    public function store(Request $request)
    {
        Vehical::create([
            'vehical_name'  => $request['vehical_name'],
            'type_id'       => $request['type_id'],
            ]);
        return redirect('vehical');
    }

    
    public function show(vehicalType $vehicalType)
    {
        //
    }

    
    public function edit($id)
    {

         $vehicl = Vehical::find($id);
        return view( 'user.vehicalsEdit', compact('vehicl'));
       
    }

      
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $vehical = Vehical::findOrFail($id);
        

        $vehical->update($input);
        return redirect()->route('vehical.index');
    }

    
    public function destroy($id)
    {
        $vehical = Vehical::find($id);
    
     
       
        $vehical->delete();
        return Redirect::route('vehical.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
   
}

resources/views/layout/users/userheader.blade.php
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>Loader </title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Preview page of Metronic Admin Theme #4 for statistics, charts, recent events and reports" name="description" />
        <meta content="" name="author" />
       <meta name="csrf-token" content="{{ csrf_token() }}">

        @section('styles')
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css" />
       <!--   -->
        <link href="{{asset('assets/global/plugins/morris/morris.css')}}" rel="stylesheet" type="text/css" />
        <!--  --> 
        <link href="{{asset('assets/global/css/components-rounded.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{{asset('assets/global/css/plugins.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/layouts/layout4/css/layout.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assets/layouts/layout4/css/themes/default.min.css')}}" rel="stylesheet" type="text/css" id="style_color" />
        <link href="{{asset('assets/layouts/layout4/css/custom.min.css')}}" rel="stylesheet" type="text/css" />
     <

        @show

        <script type="text/javascript">
            var BASE_URL = "{{ url('/')}}";
        </script>
        <link rel="shortcut icon" href="favicon.ico" /> </head>

    <body class="page-container-bg-solid page-header-fixed page-sidebar-closed-hide-logo">
        <div class="page-header navbar navbar-fixed-top">
            <div class="page-header-inner ">
                <div class="page-logo">
                    <a href="{{route('admin.dashboard')}}">
                        <img src="{{ asset('assets/pages/img/loader_logo.png')}}" alt="logo" class="logo-default" style="width: 40px; height: 40px; margin-top: 15px;" /> </a>
                    <div class="menu-toggler sidebar-toggler">
                    </div>
                </div>
             
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>

                <div class="page-actions">
                    
                </div>

                <div class="page-top">

                    
                    <div class="top-menu">
                        <ul class="nav navbar-nav pull-right">
                            <li class="separator hide"> </li>
    
                            </li>
                           
                            <li class="dropdown dropdown-user dropdown-dark">
            
                               
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <span class="username username-hide-on-mobile"> {{ Auth::user()->fname }} {{ Auth::user()->lname }} </span>
                                   
                                    <img alt="" class="img-circle" style="width: 35px; height: 35px;" src="{{asset('images/user/profile')}}/{{Auth::user()->images}}" /> </a>
                                <ul class="dropdown-menu dropdown-menu-default">
                                    <li>
                                        <a href="{{ route('userResources.show', Auth::guard('web')->id()) }}">
                                            <i class="icon-user"></i> My Profile </a>
                                    </li>
                                    
                                    
                                    <li>
                                        <a href="{{ route('user.logout') }}">
                                            <i class="icon-key"></i> Log Out </a>
                                    </li>
                                </ul>
                               
                            </li>
                           
                            <li class="dropdown dropdown-extended quick-sidebar-toggler">
                                <span class="sr-only">Toggle Quick Sidebar</span>
                                <i class="icon-logout"></i>
                            </li>

                        </ul>
                    </div>

                </div>

            </div>

        </div>

        <div class="clearfix"> </div>

        <div class="page-container">
            <div class="page-sidebar-wrapper">

                @include('layout.users.sidebar.left_sidebar')
                
            </div>
            @yield('content')


       
        <div class="quick-nav-overlay"></div>

        @section('javascripts')
     

        <script src="{{asset('assets/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/js.cookie.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/jquery.blockui.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/morris/morris.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/morris/raphael-min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/counterup/jquery.waypoints.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/counterup/jquery.counterup.min.js')}}" type="text/javascript"></script>
    
        <script src="{{asset('assets/global/plugins/horizontal-timeline/horizontal-timeline.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/flot/jquery.flot.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/flot/jquery.flot.resize.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/flot/jquery.flot.categories.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/jquery.sparkline.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/global/plugins/moment.min.js')}}" type="text/javascript"></script>

        <script src="{{asset('assets/global/scripts/app.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/pages/scripts/dashboard.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/layouts/layout4/scripts/layout.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/layouts/layout4/scripts/demo.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/layouts/global/scripts/quick-sidebar.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('assets/layouts/global/scripts/quick-nav.min.js')}}" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
        <script>
            $(document).ready(function()
            {
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
        </script>

          <script type="text/javascript">
             $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
             
         </script>
         

         @show



    </body>

</html>