routes/web.php
<?php

Route::get('/', 'PublicHomeController@index');
// Route::get('/', function () {
// 	//return Redirect::route('user-register.index');

//    // return view('public.home');
// });


Route::get('/check-me', function(){
	$captains =App\Captain::with('rates')->get();
  //App\Http\Resources\CaptainCollection::withoutWrapping();
	$data=new App\Http\Resources\CaptainCollection($captains);

	return $data;
});

Route::get('/custom_offer' ,'ScheduleController@custom_offer')->name('custom_offer');
Route::get('/weakly_offer' ,'ScheduleController@weakly_offer')->name('weakly_offer');
Route::get('/yearly_offer' ,'ScheduleController@yearly_offer')->name('yearly_offer');
Route::get('/monthly_offer' ,'ScheduleController@monthly_offer')->name('monthly_offer');
//////Admin Routes;
Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	

/////user Dashboard
Route::prefix('user')->group(function(){
 // Authentication Routes...
	Auth::routes();
	Route::get('/profile', 'User\UserResource@profile')->name('user.profile');
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::post('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::Resource('advance-booking','User\AdvanceBookingController');
	Route::Resource('good','User\GoodsController');
	Route::Resource('vehical','User\VehicalTypeController');
	Route::Resource('booking','User\BookingController');
	Route::Resource('Ride','User\RidesController');
	Route::get('pending-Ridess', 'User\RidesController@pendingride')->name('pending-Rides');
	Route::Resource('googlemap' ,'User\GoogleMapController');
	Route::Resource('userResources' ,'User\UserResource');
	Route::get('user-walletss/{id}', 'User\UserResource@walletShow');
	

});

Route::prefix('admin')->group(function(){

	Route::get('/giveme','Admin\RoleController@giveme');
	Route::get('/checkme','Admin\RoleController@checkme');

	////Accounts
	Route::resource('code','Admin\Account\AccountCodeController');
	Route::resource('bank-deposit','Admin\Account\BankDepositController');
	Route::resource('bank-payment','Admin\Account\BankPaymentController');
	Route::resource('cash-payment','Admin\Account\CashPaymentController');
	Route::resource('cash-reciept','Admin\Account\CashRecieptController');
	Route::resource('invoice','Admin\Account\InvoiceController');
	Route::resource('journal-voucher','Admin\Account\JvController');
	Route::resource('ledger','Admin\Account\LedgerController');
	Route::resource('financials','Admin\Account\FinancialController');
	Route::resource('payable','Admin\Account\PayableAccountController');
	Route::resource('receivable','Admin\Account\RecivableController');
	Route::get('/accounts/detail','Admin\Account\LedgerController@all_account_record')->name('code.all_account');
	Route::post('code/create','Admin\Account\AccountCodeController@create_form')->name('account.new_acc');
Route::post('code/get_account', 'Admin\Account\AccountCodeController@get_account')->name('get_account');
Route::post('recivable/reciveable_account_record','Admin\Account\RecivableController@reciveable_account_record')->name('reciveable_account_record');
Route::post('payable/payables_account_record','Admin\Account\PayableAccountController@payables_account_record')->name('payables_account_record');
Route::post('/ledger/ledger_detail', 'Admin\Account\LedgerController@ledger_detail')->name('ledger_detail');
Route::post('ledger/search/record','Admin\Account\LedgerController@search_ledger_amount')->name('search_ledger_amount');

	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	
	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

	Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::Resource('userResource' ,'UserResource');

	Route::get('/user/send','UserResource@send');
Route::get('delete_record/{id}' ,'UserResource@delete_record');
	Route::post('/user_data','UserResource@get_users')->name('get-data');
	Route::post('/user_status','UserResource@user_change_status')->name('user-change-status');

	Route::get('/booking-detail/{id}' ,'UserResource@bookingdetail')->name('booking-detail');
	Route::get('user-wallet/{id}', 'UserResource@walletShow')->name('user-wallet');

	Route::Resource('adminResource' ,'AdminResource');

	Route::post('/admin_data','AdminResource@get_admin')->name('get-admin');
	Route::post('/admin_status','AdminResource@admin_change_status')->name('admin-change-status');
Route::get('admin_delete_record/{id}' ,'AdminResource@delete_record');

	Route::Resource('captainResource' ,'CaptainResource');

	Route::post('/captain_account', 'CaptainResource@captain_account')->name('captain_account');

	Route::post('/captain_getsss','CaptainResource@get_captain')->name('get-captainss');
	Route::post('/change_status','CaptainResource@captain_change_status')->name('captain-change-status');
Route::get('captain/delete_record/{id}' ,'CaptainResource@delete_record');
	Route::get('captain-wallet/{id}', 'CaptainResource@walletShow')->name('captain-wallet');


	Route::Resource('goods' ,'GoodsController');
	Route::get('good_delete_record/{id}' ,'GoodsController@delete_record');
	Route::get('good/delete_record/{id}' ,'GoodsController@delete_record');
	Route::post('/get_good','GoodsController@get_good')->name('get-good');
	Route::post('/good_status','GoodsController@good_change_status')->name('good-change-status');

	Route::Resource('captain-wallet' ,'CaptainWalletController');
	Route::Resource('googlemaps' ,'GoogleMapController');
	Route::Resource('vehicals', 'VehicalTypeController');
	Route::get('vehicals/delete_record/{id}' ,'VehicalTypeController@delete_record');
	Route::post('/get_vehical','VehicalTypeController@get_vehical')->name('get_vehical');
	Route::post('/vehical_change_status','VehicalTypeController@vehical_change_status')->name('vehical-change-status');
	

	Route::Resource('bookings', 'BookingController');
	Route::post('/booking_data','BookingController@get_booking')->name('get-booking');

	Route::Resource('pending-booking', 'PendingBookingController');
	Route::post('/pending_booking_data','PendingBookingController@get_pendingbooking')->name('get-pending-booking');



	Route::Resource('advance-bookings', 'AdvanceBookingController');

	Route::Resource('Rides' , 'RidesController');
	Route::post('/ride-data','RidesController@get_ride')->name('get-ride');
	
	Route::get('pending-Rides', 'RidesController@pendingride')->name('pendingRide');
	Route::post('/pending_data','RidesController@get_pending')->name('get-pending');

	Route::post('/upload_document_file','CaptainResource@upload_document_file')->name('upload_document_file');
	Route::post('/remove_document_file','CaptainResource@remove_document_file')->name('remove_document_file');

	Route::get('search','CaptainResource@searchbar')->name('searching');
	Route::Resource('good-categories' , 'GoodCategoriesController');
	Route::post('/get_cat','GoodCategoriesController@get_cat')->name('get_cat');
	Route::post('/cat_status','GoodCategoriesController@categories_change_status')->name('cat-change-status');

	Route::Resource('vehicle-sub-categories' , 'VehicleSubCategoriesController');
	Route::get('vehicle_delete_record/{id}' ,'VehicleSubCategoriesController@delete_record');
	Route::post('/get_sub_vehical','VehicleSubCategoriesController@get_sub_vehical')->name('get_sub_vehical');
	Route::post('/vcategories_change','VehicleSubCategoriesController@vcategories_change_status')->name('vcategories_change_status');
	Route::get('vehicle_categoires', 'VehicleSubCategoriesController@select_vehicle_categories')->name('vehicle-categories_data');

	Route::Resource('vehical-categories' , 'VehicalCategoriesController');
		Route::get('vehicle_categories_delete_record/{id}' ,'VehicalCategoriesController@delete_record');
	Route::post('/get_cat_vehical','VehicalCategoriesController@get_cat_vehical')->name('get-cat-vehical');
	Route::post('/categories_change_status','VehicalCategoriesController@categories_change_status')->name('category-change-status');

	Route::resource('roles', 'RoleController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('financial', 'FinancialController');

	Route::get('report/{id}', 'CaptainReportController@report');
	Route::get('captain_report' ,'CaptainReportController@filtercaptain')->name('captain_report');
	
	Route::resource('report' , 'CaptainReportController');

	Route::get('/get-captains-ajax' ,'CaptainResource@get_captains_ajax');
	Route::resource('inflow' , 'TransactionController' );
	Route::post('/traction','TransactionController@tracking_datas')->name('transaction-history');
	Route::resource('/emergencies','EmergencyController');
	Route::get('emergency_delete_record/{id}' ,'EmergencyController@delete_record');
		Route::post('/get_emergencies','EmergencyController@get_emergnecies')->name('get-emergencies');
		Route::post('/emergencies_change_status','EmergencyController@emergnecies_change_status')->name('emergencies-change-status');


	Route::resource('/offers','OfferController');
	Route::get('offer_delete_record/{id}' ,'OfferController@delete_record');
		Route::post('/get_offer','OfferController@get_offers')->name('get-offer');
		Route::post('/offer_change_status','OfferController@offerschange_status')->name('offer-change-status');

	Route::Resource('skip-reasons' ,'SkipReasonController');

resources/views/admin/emergency.blade.php
<?php
/**
 * Project: Loader.
 * User: Shafqat
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>
@extends('_layouts.admin.app')
@section('content')
    <div class="m-portlet m-portlet--mobile">


        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                      Emergencies Section
                    </h3>
                </div>
            </div>
        </div>
        @component('_components.alerts-default')
        @endcomponent

        <div class="m-portlet__body">

            <!--begin: Search Form -->
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-4">
                                <div class="btn-group">
                                        <a href="{{ route('emergencies.create')}}" id="sample_editable_1_new" class="btn btn-success" style="position: relative;top: -10px;"> Add New
                                            </i>
                                        </a>

                                    </div>
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                                    <span class="m-input-icon__icon m-input-icon__icon--left">
                                                            <span>
                                                                <i class="la la-search"></i>
                                                            </span>
                                                        </span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!--end: Search Form -->

            <div class="m_datatable" id="child_data_ajax"></div>
        </div>


    </div>


@endsection

@push('post-scripts')

<@if(session('success_message')) 

<script type="text/javascript">
   swal({
      title: "Good job!",
      text: "You record delete sucessfully",
      icon: "success",
      button: "Aww yiss!"
  });
</script>
@endif 

    <script type="application/javascript">

    var datatable = $('.m_datatable').mDatatable({
    // datasource definition
    data: {
    type: 'remote',
    source: {
    read: {
    url: BASE_URL+'/admin/get_emergencies'
    }
    },
    pageSize: 10, // display 20 records per page
    saveState: {
    cookie: false,
    webstorage: false
    },
    serverPaging: true,
    serverFiltering: true,
    serverSorting: true
    },

    // layout definition
    layout: {
    theme: 'default',
    scroll: false,
    height: null,
    footer: false
    },

    // column sorting
    sortable: true,

    pagination: true,

    detail: false,

    search: {
    input: $('#generalSearch')
    },

    // columns definition
    columns: [ 
   
        {
            field: "emergencies_name",
            title: "Emergencies name",
            
        },
            {
                field:"description",
                title:"Emergencies description ",
            },
        {
        field: "status",
        title: "Status",
        template: function (row) {
            // return row.status;
                return row.status?`<a href="javascript:;" onclick="change_status(this,${row.id},0)" class="btn btn-success">Active</a>`:`<a href="javascript:;" onclick="change_status(this,${row.id},1)" class="btn btn-danger">Deactive</a>`;
            }
        },
        {
                field: "Actions",
            
                title: "Actions",
                sortable: false,
                overflow: 'visible',
                template: function (row) {

                    
                    return '\
                        <a href="admin/emergencies/'+row.id+'/edit" class="btn btn-warning btn-xs" style="padding:5px;font-size:12px;">\
                            edit</i>\
                        </a>\
                         <a href="admin/emergency_delete_record/'+row.id+'" class="btn btn-danger btn-xs" title="show details" style="padding:5px;font-size:12px;" onclick="delete_record(this); return false;">\
                            delete\
                        </a>\
                    ';
        }
    }
    ]
    });

    </script>
    <script type="text/javascript">

  function change_status(obj,id,activity) {
    console.log(id,activity);
      $.ajax({
        url: "{{ route('country-change-status') }}", 
        method:"POST",
        data:{'user_id':id,'activity':activity},
        // dataType:"text",
        success: function(response){
            // console.log(response);return false;
            if(response.activity){
                if(activity)
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',0)" class="btn btn-success"> Active </a>');
                else
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',1)" class="btn btn-danger"> Deactive </a>');

                toastr.success(response.message);
                console.log(activity);
            }else{
               toastr.error(response.message);

           }
       }});

  }

</script>


   

@endpush

resources/views/admin/goodscategories.blade.php
@extends('layout.admin.headerAdmin')
@section('content')
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="portlet light portlet-fit bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-truck" style="color: #fff;"></i>
                                        <span class="caption-subject font-red sbold uppercase">Goods Categories</span>
                                    </div>
                                   
                                </div>
                                <div class="portlet-body">
                                    <div class="table-toolbar">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="btn-group"> 
                                                    <a href="{{route('good-categories.create')}}" class="btn green"> Add New
                                                        <i class="fa fa-plus"></i>
                                                    </a href="{{route('good-categories.create')}}">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="btn-group pull-right">

                                                    

                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            
                                        </div>
                                        
                                    </div>
                                    <div class="table-responsive">
                                    <table class="table table-striped table-hover table-bordered" id="category">
                                       <thead>
                                            <tr>
                                             <th align="left">
                                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                                        <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                                        <span></span>
                                                    </label>
                                                </th>
                                                <th> Categories Name </th>
                                                <th> Status </th>
                                                <th> Action </th>
                                            </tr>
                                        </thead>
                                        
                                    </table>
                                    </div>
                                    
                                </div>

                                
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
               

                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>
          
            <a href="javascript:;" class="page-quick-sidebar-toggler">
                <i class="icon-login"></i>
            </a>
             <div class="modal fade" id="add_new_modal" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Modal Header</h4>
                        </div>
                    <div class="modal-body">
                        <div class="tab-pane active" id="tab_0">
                                <div class="portlet box green">
                                          <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="fa fa-gift"></i>Categories Add  
                                                </div>
                                                <div class="tools">
                                                    <a href="javascript:;" class="collapse"> </a>
                                                    <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                                                    <a href="javascript:;" class="reload"> </a>
                                                    <a href="javascript:;" class="remove"> </a>
                                                </div>
                                          </div>
                                                <div class="portlet-body form">
                                                    <!-- BEGIN FORM-->
                                                    <form action="{{ route('good-categories.store') }}" class="form-horizontal" method="POST">
                                                        {{ csrf_field() }}
                                                                <div class="form-body">
                                                                    <div class="form-group">
                                                                        <label class="col-md-3 control-label" style="font-size: 13px;"> categories Name</label>
                                                                        <div class="col-md-4">
                                                                            <input type="text" class="form-control input-circle" placeholder="Categories" name="name" required>
                                                                            
                                                                        </div>
                                                                    </div>


               
                                                                </div> 
                                                                
                                                                <div class="form-actions">
                                                                    <div class="row">
                                                                        <div class="col-md-offset-3 col-md-9">
                                                                            <button type="submit" class="btn btn-circle green">Submit</button>
                                                                            <button type="button" class="btn btn-circle grey-salsa btn-outline">Cancel</button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                     </form>
                                                </div>
                                            <div class="modal-footer">
                                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            </div>
                                </div>
                        </div>
                   </div>
                </div>   
             </div>
           </div>  
            
          
 @endsection       <!-- BEGIN FOOTER -->

@section('styles')
    @parent
    <link href="{{ asset('assets/global/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />

    <link href="{{ asset('assets/apps/css/stylebutton.css') }}" rel="stylesheet" type="text/css" />
     <link href="{{ asset('assets/apps/css/jquery.dataTables.css') }}" rel="stylesheet" type="text/css" />
     
     <style type="text/css">
         td a {
            float: left;
         }
     </style>
@endsection

@section('javascripts')
@parent


<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js" type="text/javascript"></script>




<script>
            $('#category').DataTable( {
                "processing": true,
                "serverSide": true,

                Length:10,
                ajax: {
                    "url":"<?= route('get_cat') ?>",
                    "dataType":"json",
                    "type":"POST"
                },

                columns:[
                    {"data":"id","render":function(id){
                       return  '<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline"> <input type="checkbox" class="checkboxes" value="'+id+'" />  <span></span></label>'; 
                   },"searchable":false,"orderable":false},
                    
                    {"data":"name"},
                    
                    {"data":"status","render":function(status,type,row){
                        return status?'<a href="javascript:;" onclick="change_status(this,'+row.id+',0)" class="btn btn-success"> Active </a>':'<a href="javascript:;" onclick="change_status(this,'+row.id+',1)" class="btn btn-danger"> Deactive </a>';
                    }},
                    {"data":"id","render":function(id){
                        confirmInit();
                        var edit_route = '{{ route("good-categories.edit", ":id") }}';
                            edit_route = edit_route.replace(':id', id);

                             var delete_route = '{{ route("good-categories.destroy", ":id") }}';
                                delete_route = delete_route.replace(':id', id);

          var buttons = '<a href="'+edit_route+'" class="btn btn-warning btn-xs">Edit</a>';

          buttons +='<a href="javascript:;" data-toggle="confirmation" data-placement="left" onclick="delete_row(this,'+id+')" data-action="'+delete_route+'" class="btn btn-danger btn-xs">Delete</a>';

          return buttons;
                    },"searchable":false,"orderable":false}
                ]

                
            } );
        </script>
 <script type="text/javascript">
            
      function change_status(obj,id,status) {
             
          $.ajax({
            url: "{{ route('cat-change-status') }}", 
            method:"POST",
            data:{'user_id':id,'status':status},
            success: function(response){
                if(response.status){
                if(status)
                $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',0)" class="btn btn-success"> Active </a>');
                else
                $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',1)" class="btn btn-danger"> Deactive </a>');

                 toastr.success(response.message);

                }else{
                 toastr.error(response.message);

                }
           }});

            }

        </script>



<!-- <script type="text/javascript">
    $(document).ready(function() {
    $('#captain').DataTable( {
        dom: 'Bfrtip',

        "paging": false,
        "bInfo": false,
        "searching": false,
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );
</script> -->
<script>
$(document).ready(function(){
    $('.wallet').tooltip({title: "Wallet"}); 
    $('.show').tooltip({title: "show!"}); 
    $('.edit').tooltip({title: "Edit"});
    $('.pdf').tooltip({title: "report in pdf"});
});
</script>



<script type="text/javascript">
var action_url ;
var user_id ;
var row_obj;
function delete_row(obj,id) {
        action_url = $(obj).attr('data-action');
        user_id = id;
        row_obj = obj;
          confirmInit();
       $(obj).on('confirmed.bs.confirmation', function () {
         
          $.ajax({
            url: action_url, 
            method:"DELETE",
            data:{'id':user_id},
            success: function(response){
                if(response.status){
                    $(row_obj).parent().parent().remove();
                }
                else{
                    console.log(response.message);
               }
           }});
        });

       

    }    
    
function delete_action() {
var r = confirm("Are you sure you want to delete this!");
if (r == true) {
   return true;
} else {
   
       return false;
}
    }



</script>

@endsection