routes/web.php
	Route::Resource('pending-booking', 'PendingBookingController');
	Route::post('/pending_booking_data','PendingBookingController@get_pendingbooking')->name('get-pending-booking');



	Route::Resource('advance-bookings', 'AdvanceBookingController');

	Route::Resource('Rides' , 'RidesController');
	Route::post('/ride-data','RidesController@get_ride')->name('get-ride');
	
	Route::get('pending-Rides', 'RidesController@pendingride')->name('pendingRide');
	Route::post('/pending_data','RidesController@get_pending')->name('get-pending');

	Route::post('/upload_document_file','CaptainResource@upload_document_file')->name('upload_document_file');
	Route::post('/remove_document_file','CaptainResource@remove_document_file')->name('remove_document_file');

	Route::get('search','CaptainResource@searchbar')->name('searching');
	Route::Resource('good-categories' , 'GoodCategoriesController');
	Route::post('/get_cat','GoodCategoriesController@get_cat')->name('get_cat');
	Route::post('/cat_status','GoodCategoriesController@categories_change_status')->name('cat-change-status');

	Route::Resource('vehicle-sub-categories' , 'VehicleSubCategoriesController');
	Route::get('vehicle_delete_record/{id}' ,'VehicleSubCategoriesController@delete_record');
	Route::post('/get_sub_vehical','VehicleSubCategoriesController@get_sub_vehical')->name('get_sub_vehical');
	Route::post('/vcategories_change','VehicleSubCategoriesController@vcategories_change_status')->name('vcategories_change_status');
	Route::get('vehicle_categoires', 'VehicleSubCategoriesController@select_vehicle_categories')->name('vehicle-categories_data');

	Route::Resource('vehical-categories' , 'VehicalCategoriesController');
		Route::get('vehicle_categories_delete_record/{id}' ,'VehicalCategoriesController@delete_record');
	Route::post('/get_cat_vehical','VehicalCategoriesController@get_cat_vehical')->name('get-cat-vehical');
	Route::post('/categories_change_status','VehicalCategoriesController@categories_change_status')->name('category-change-status');

	Route::resource('roles', 'RoleController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('financial', 'FinancialController');

	Route::get('report/{id}', 'CaptainReportController@report');
	Route::get('captain_report' ,'CaptainReportController@filtercaptain')->name('captain_report');
	
	Route::resource('report' , 'CaptainReportController');

	Route::get('/get-captains-ajax' ,'CaptainResource@get_captains_ajax');
	Route::resource('inflow' , 'TransactionController' );
	Route::post('/traction','TransactionController@tracking_datas')->name('transaction-history');
	Route::resource('/emergencies','EmergencyController');
	Route::get('emergency_delete_record/{id}' ,'EmergencyController@delete_record');
		Route::post('/get_emergencies','EmergencyController@get_emergnecies')->name('get-emergencies');
		Route::post('/emergencies_change_status','EmergencyController@emergnecies_change_status')->name('emergencies-change-status');


	Route::resource('/offers','OfferController');
	Route::get('offer_delete_record/{id}' ,'OfferController@delete_record');
		Route::post('/get_offer','OfferController@get_offers')->name('get-offer');
		Route::post('/offer_change_status','OfferController@offerschange_status')->name('offer-change-status');

	Route::Resource('skip-reasons' ,'SkipReasonController');
		Route::get('reasons_delete_record/{id}' ,'SkipReasonController@delete_record');
	Route::post('/get_reasons','SkipReasonController@get_reasons')->name('get_reasons');
	Route::post('/reasons_status','SkipReasonController@reasons_change_status')->name('reasons-change-status');

	Route::Resource('activity-logs' ,'AcivityLogController');
	Route::post('/get-activity-log','AcivityLogController@get_logs')->name('get_activity_log');

///////CMS setting updated here ////////
	Route::resource('logo', 'Cms\LogoController');
	Route::resource('slide', 'Cms\SliderController');
	Route::resource('public-home-page' , 'Cms\PublicHomeController');
	Route::resource('drive-section' , 'Cms\DriveController');
	Route::resource('Bussiness-section', 'Cms\BussinessController');
	Route::resource('companies-section' , 'Cms\CompaniesController');
	Route::resource('news-section' , 'Cms\NewsController');
	Route::resource('out-flow', 'OutflowController');
	Route::post('/outflow_data','OutflowController@outflow_data')->name('outflow-data');

	Route::get('/main_wallet','OutflowController@main_wallet')->name('main-wallet-data');

	Route::get('user-report/{id}', 'UserReportController@report');
	Route::get('report-filter' ,'UserReportController@filteruser')->name('report-user-filter');
	Route::resource('finance-report' , 'UserReportController');

	Route::post('report-betwenreport' ,'UserReportController@betwenreport')->name('report-betwenreport');

	Route::Resource('cities' ,'CityController');
	Route::get('city_delete_record/{id}' ,'CityController@delete_record');
	Route::get('city-data' ,'CityController@city_on_select')->name('city_data');
	Route::post('/get_citi','CityController@get_citi')->name('get-citi');
	Route::post('/citi_status','CityController@citi_change_status')->name('citi-change-status');

	Route::Resource('country' ,'CountriesController');
	Route::get('country_delete_record/{id}' ,'CountriesController@delete_record');
	Route::post('/get_country','CountriesController@get_country')->name('get-country');
	Route::post('/country_status','CountriesController@country_change_status')->name('country-change-status');

 
 	Route::get('branch-data' ,'BranchController@branch_on_select')->name('branch_data');
	Route::Resource('branch' ,'BranchController');
	Route::get('branch_delete_record/{id}' ,'BranchController@delete_record');
	Route::post('/get_branch','BranchController@get_branch')->name('get-branch');
	Route::post('/branch_status','BranchController@branch_change_status')->name('branch-change-status');

	Route::Resource('franchise' ,'FranchiseController');
	Route::get('franchise_delete_record/{id}' ,'FranchiseController@delete_record');
	Route::post('/get_franchise','FranchiseController@get_franchise')->name('get-franchise');
	Route::post('/franchise_status','FranchiseController@franchise_change_status')->name('franchise-change-status');

// Route for export/download tabledata to .csv, .xls or .xlsx
Route::get('completeRideExcel/{type}', 'RidesController@complete_ride_download')->name('completeRideExcel');
Route::get('adminExcel/{type}', 'AdminResource@downloadExcel')->name('adminExcel');
Route::get('captainExcel/{type}', 'CaptainResource@downloadExcel')->name('downloadExcel');

Route::get('transactionExcel/{type}', 'TransactionController@downloadExcel')->name('downloadExcel');
Route::get('bookingExcel/{type}', 'BookingController@downloadExcel')->name('downloadExcel');
Route::get('pbookingExcel/{type}', 'PendingBookingController@downloadExcel')->name('downloadExcel');
Route::get('transactionExcel/{type}', 'TransactionController@downloadExcel')->name('transactionExcel');
Route::get('pendingExcel/{type}', 'RidesController@pending_ride_download')->name('pendingExcel');
Route::get('captainCommisionExcel/{type}', 'OutflowController@downloadExcel')->name('captainCommissionExcel');



});
///////////// end Admin DASHBOARD START HERE............. /////////////////

//////Captain Routes;   ////////
Route::prefix('captain')->group(function(){
	Route::get('/', 'CaptainController@index')->name('captain.dashboard');
	Route::post('/register', 'Auth\CaptainRegisterController@create')->name('captain.register');
	Route::get('/login', 'Auth\CaptainLoginController@showLoginForm')->name('captain.login');
	Route::post('/login', 'Auth\CaptainLoginController@login')->name('captain.login.submit');
	Route::get('/logout', 'Auth\CaptainLoginController@captainLogout')->name('captain.logout');
	Route::post('/logout', 'Auth\CaptainLoginController@captainLogout')->name('captain.logout');
///////captain

	Route::get('/password/reset', 'Auth\CaptainForgotPasswordController@showLinkRequestForm')->name('captain.password.request');
	Route::post('/password/email', 'Auth\CaptainForgotPasswordController@sendResetLinkEmail')->name('captain.password.email');
	Route::get('/password/reset/{token}', 'Auth\CaptainResetPasswordController@showResetForm')->name('captain.password.reset');
	Route::post('/password/reset', 'Auth\CaptainResetPasswordController@reset');

//////////captain dashboard

	Route::Resource('advancebooking','captain\AdvanceBookingController');
// Route::Resource('good-categories' , 'GoodCategoriesController');
// Route::Resource('vehical-categories' , 'VehicalCategoriesController');
	Route::Resource('captain-good','captain\GoodsController');
	Route::Resource('captain-vehical','captain\VehicalTypeController');
	Route::Resource('captain-booking','captain\BookingController');
	Route::Resource('captain-Ride','captain\RidesController');
	Route::get('pendingRidese', 'captain\RidesController@pendingride')->name('pendingRidee');
	Route::Resource('captain-googlemap' ,'captain\GoogleMapController');
	Route::Resource('captain-Resources' ,'captain\CaptainResource');
	Route::get('captain-wallet/{id}', 'captain\CaptainResource@walletShow');
//get-captains-ajax
});

Route::get('ride', 'PublicHomeController@ride')->name('ride');
Route::get('sign', 'PublicHomeController@signin')->name('sign-in');
Route::post('logout', 'PublicHomeController@logout')->name('public.logout');
Route::Resource('user-register', 'PublicHomeController');
Route::post('login', 'PublicHomeController@login')->name('login');
Route::Resource('fare-estimate' ,'web\FareEstimateController');
Route::get('drive' ,'web\DriveController@index')->name('drive');
Route::get('drive-app' ,'web\DriveController@drivapp')->name('drive-app');
Route::get('drive-requirement' ,'web\DriveController@drive_requirement')->name('drive-requirement');
Route::get('drive_safety' , 'web\DriveController@drive_safety')->name('drive_safety');
Route::get('how-it-work', 'web\RideController@howitwork')->name('how-it-work');

app/Franchise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Franchise extends Model
{
    protected $fillable = array('name', 'address' , 'branch_id');

    public function branch()
    {
    	return $this->belongsTo(Branch::class ,'branch_id');
    }
}

app/Http/Controllers/FranchiseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use App\Franchise;
use App\Branch;
use Session;
class FranchiseController extends Controller
{
   
    public function __construct()
    {
        $this->middleware(['auth:admin']);
    }
    
    public function index()
    {
       
        return view('admin.franchise.franchise_index');
    }

    
    public function create()
    {
        $branch_data = Branch::all();
        return view('admin.franchise.franchiseCreate' , compact('branch_data'));
        
    }

    
    public function store(Request $request)
    {
         $validator = Validator::make($request->all(),
        [
        'name' => 'required|max:40||unique:franchises',
        'address' => 'required',
        'branch_id' => 'required'
   
        ]);

       if($validator->fails())
       {
            $message = $validator->errors()->first();
            Session::flash('info', " $message") ;
            return Redirect::back()->withErrors($validator);
       } 
       else
       {
        $franchise_affected = Franchise::create([
            'name'          => $request['name'],
            'address'          => $request['address'],
            'branch_id'          => $request['branch_id'],
            ]);

        if($franchise_affected)
        session()->flash('success', 'Record has been added. successfully.');
        else
        session()->flash('danger', 'Fail to update the record.');

        return redirect()->route('franchise.index');
        }
    }
    
    public function show(Request $request)
    {
        
    }

    
    public function edit($id)
    {
         $franchise_data = Franchise::find($id);
          $branch_data = Branch::all();
    
        return view('admin.franchise.franchiseEdit', compact( 'franchise_data' ,'branch_data'));
        
    }

    
    public function update(Request $request, $id)
    {
        $branch_item = Franchise::findOrFail($id);
        $input = $request->all();

        $branch_affected = $branch_item->update($input);

        if($branch_affected)
        session()->flash('success', 'Record has been added. successfully.');
        else
        session()->flash('danger', 'Fail to update the record.');
        return redirect()->route('franchise.index');
    }

   
    public function delete_record($id)
    {
        $Branch_item = Franchise::find($id);

        $branch_item_destory = $Branch_item->delete();

        if($branch_item_destory){
        $response['status'] = true;
        session()->flash('success_message', 'Record has been delete. successfully.');
        $response['message'] = "Record has been delete Successfully.";
        }else{
        $response['status'] = false; 
        $response['message'] = "Fail to delete Record.";
        }
        return redirect()->route('franchise.index');
    } 

     public function get_franchise(Request $request)
    {

    
    $datatable = ! empty( $request->datatable ) ? $request->datatable : array();
        $datatable = array_merge( array( 'pagination' => array(), 'sort' => array(), 'query' => array() ), $datatable );

        $sort  = ! empty( $datatable[ 'sort' ][ 'sort' ] ) ? $datatable[ 'sort' ][ 'sort' ] : 'desc';
        $field = ! empty( $datatable[ 'sort' ][ 'field' ] ) ? $datatable[ 'sort' ][ 'field' ] : 'id';

        $page    = ! empty( $datatable[ 'pagination' ][ 'page' ] ) ? (int)$datatable[ 'pagination' ][ 'page' ] : 1;
        $perpage = ! empty( $datatable[ 'pagination' ][ 'perpage' ] ) ? (int)$datatable[ 'pagination' ][ 'perpage' ] : -1;

        $filter = isset( $datatable[ 'query' ][ 'generalSearch' ] ) && is_string( $datatable[ 'query' ][ 'generalSearch' ] ) ? $datatable[ 'query' ][ 'generalSearch' ] : '';

        $pages = 1;
        $total = Franchise::count();

        // $perpage 0; get all data
        if ( $perpage > 0 ) {
            $pages  = ceil( $total / $perpage ); // calculate total pages
            $page   = max( $page, 1 ); // get 1 page when $_REQUEST['page'] <= 0
            $page   = min( $page, $pages ); // get last page when $_REQUEST['page'] > $totalPages
            $offset = ( $page - 1 ) * $perpage;
            if ( $offset < 0 ) {
                $offset = 0;
            }

        }
        $users = Franchise::with('branch')->offset($offset)->limit($perpage)->orderBy($field,$sort);

        if ( ! empty( $filter ) ) {
            $users->where('id', 'like', "%{$filter}%")
                ->orWhere('name','like',"%{$filter}%")
                ->orWhere('status','like',"%{$filter}%")
                ->orWhere('created_at','like',"%{$filter}%");

            unset( $datatable[ 'query' ][ 'generalSearch' ] );

        }

        $data=$users->get();


        $meta = array(
            'page'    => $page,
            'pages'   => $pages,
            'perpage' => $perpage,
            'total'   => $total,
        );

        $result = array(
            'meta' => $meta + array(
                    'sort'  => $sort,
                    'field' => $field,
                ),
            'data' => $data
        );
          // print_r($result);exit();
        return  response()->json($result);

    }

    public function franchise_change_status(Request $request)
    {
         $id = $request->input('user_id');
        $status = $request->input('activity');
        $user = Franchise::find($id) ;
        $user->status  = $status;
        $effected=$user->save();
        
        $response = array();
        if($effected){
        $response['activity'] = true;
        $response['message']=" Status has been changed Successfully.";
          }else{
        $response['activity'] = false;
        $response['message']="Fail to change the user status.";
          }
        return response()->json($response, 200);


    }


}

resources/views/admin/franchise/franchiseCreate.blade.php
<?php
/**
 * Project: Loader.
 * User: Shafqat
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>

@extends('_layouts.admin.app')
@section('content')
<div class="m-portlet m-portlet--mobile">

   <div class="m-portlet__head">
    <div class="m-portlet__head-caption head_21">
        <div class="m-portlet__head-title ">
            <h3 class="m-portlet__head-text sbold uppercase">
              <i class="fa fa-car" style="color: #fff;"></i>Add New Franchise 
          </h3>
      </div>
  </div>
</div>
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">

        </div>

        <div class="tab-content">


            <div class="caption">
            </div>

        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->

            <form action="{{route('franchise.store') }}" class="form-horizontal" method="POST">
                {{ csrf_field() }}

                <div class="form-body">

                    <div class="form-group">
                        <label class="col-md-3 control-label">Franchise Name</label>
                        <div class="col-md-12">
                            <input type="text" class="form-control input-circle"  name="name" >
                                    @if ($errors->has('name'))
                                        <div class="alert alert-danger" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                              <span aria-hidden="true">×</span>
                                              <span class="sr-only">Close</span>
                                          </button>
                                          <strong>Warning!</strong> {{$errors->first('name')}}
                                      </div>
                                    @endif

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">Address</label>
                        <div class="col-md-12">
                            <input type="text" class="form-control input-circle"  name="address" >
                                    @if ($errors->has('address'))
                                        <div class="alert alert-danger" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                              <span aria-hidden="true">×</span>
                                              <span class="sr-only">Close</span>
                                          </button>
                                          <strong>Warning!</strong> {{$errors->first('address')}}
                                      </div>
                                    @endif

                        </div>
                    </div>


                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label" style="font-size: 13px;"> City Name</label>
                            <div class="col-md-12">
                                <select   class="form-control input-circle" name="branch_id" >

                                 @foreach ($branch_data as $categorie)

                                 <option  value="{{ $categorie->id }}"> {{ $categorie->name}}
                                 </option>
                                 @endforeach
                             </select>
                         </div>

                     </div>
                 </div>

             </div>

             <div class="form-actions">
           <div class=" col-md-12">
                  <div class="pull-right">
                        <button type="submit" class="btn btn-warning ">Submit</button>
                            </form>
                    <a href="{{ route('franchise.index')}}" type="button" class="btn btn-success btn-outline">Cancel</a>
                    </div>
                </div>
                <br>
            </div>
<br>
<br>
    
        <!-- END FORM-->
</div>
</div>
</div>
</div>
</div>
</div>


@endsection

resources/views/admin/franchise/franchiseEdit.blade.php
<?php
/**
 * Project: Loader.
 * User: Shafqat
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>

@extends('_layouts.admin.app')
@section('content')
<div class="m-portlet m-portlet--mobile">

 <div class="m-portlet__head">
    <div class="m-portlet__head-caption head_21">
        <div class="m-portlet__head-title ">
            <h3 class="m-portlet__head-text sbold uppercase">
              <i class="fa fa-car" style="color: #fff;"></i>Edit New Franchise 
          </h3>
      </div>
  </div>
</div>
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEAD-->
        <div class="page-head">

        </div>

        <div class="tab-content">

            <div class="caption">
            </div>

        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->


            {!! Form::open(['method' => 'PATCH' ,'files'=>true, 'route' => ['franchise.update',$franchise_data->id], 'class'=>'form-horizontal']) !!}

            <div class="form-body">

                <div class="form-group">
                    <label class="col-md-3 control-label">Franchise Name</label>
                    <div class="col-md-12">
                        <input type="text" value="{{ $franchise_data->name}}" class="form-control input-circle"  name="name" >

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Address</label>
                    <div class="col-md-12">
                        <input type="text" value="{{ $franchise_data->address}}"  class="form-control input-circle"  name="address" >

                    </div>
                </div>


                <div class="form-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label" style="font-size: 13px;"> City Name</label>
                        <div class="col-md-12">
                            <select   class="form-control input-circle" value="{{ $franchise_data->branch_id}}" name="branch_id" >

                               @foreach ($branch_data as $categorie)

                               <option  value="{{ $categorie->id }}"> {{ $categorie->name}}
                               </option>
                               @endforeach
                           </select>
                       </div>

                   </div>
               </div>

           </div>

           <div class="form-actions">
           <div class=" col-md-12">
                  <div class="pull-right">
                    <button type="submit" class="btn btn-info green">Submit</button>
                     {!! Form::close() !!}
                    <button type="button" class="btn btn-success ">Cancel</button>
                </div>
            </div>
        </div>

       
        <!-- END FORM-->
    </div> 
</div>
</div>
</div>
</div>
</div>



@endsection

resources/views/admin/franchise/franchise_index.blade.php
<?php
/**
 * Project: Loader.
 * User: Shafqat
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>

@extends('_layouts.admin.app')
@section('content')
<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title" style="background-color:#f26727;">
                <h3 class="m-portlet__head-text">
                  Franchise Record 
              </h3>
          </div>
      </div>
  </div>
  @component('_components.alerts-default')
  @endcomponent

  <div class="m-portlet__body">

    <!--begin: Search Form -->
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
        <div class="row align-items-center">
            <div class="col-xl-8 order-2 order-xl-1">
                <div class="form-group m-form__group row align-items-center">
                    <div class="col-md-4">
                        <div class="btn-group">
                            <a href="{{ route('franchise.create')}}" id="sample_editable_1_new" class="btn btn-success" style="position: relative;top: -10px;"> Add New
                            </i>
                        </a>

                    </div>
                    <div class="m-input-icon m-input-icon--left">
                        <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                        <span class="m-input-icon__icon m-input-icon__icon--left">
                            <span>
                                <i class="la la-search"></i>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end: Search Form -->

    <div class="m_datatable" id="child_data_ajax"></div>
</div>


</div>


@endsection

@push('post-scripts')
<@if(session('success_message')) 

<script type="text/javascript">
   swal({
      title: "Good job!",
      text: "You record delete sucessfully",
      icon: "success",
      button: "Aww yiss!"
  });
</script>
@endif 
<script type="application/javascript">

    var datatable = $('.m_datatable').mDatatable({
    // datasource definition
    data: {
        type: 'remote',
        source: {
            read: {
                url: BASE_URL+'/admin/get_franchise'
            }
        },
    pageSize: 10, // display 20 records per page
    saveState: {
        cookie: false,
        webstorage: false
    },
    serverPaging: true,
    serverFiltering: true,
    serverSorting: true
},

    // layout definition
    layout: {
        theme: 'default',
        scroll: false,
        height: null,
        footer: false
    },

    // column sorting
    sortable: true,

    pagination: true,

    detail: false,

    search: {
        input: $('#generalSearch')
    },

    // columns definition
    columns: [ 

    {
        field: "name",
        title: "Branch Name",

    },
    {
        field: "branch_id",
        title: " Name",
        template:function(row){
            return row.branch.name;
        }

    },
    {
        field: "status",
        title: "Status",
        template: function (row) {
            // return row.status;
            return row.status?`<a href="javascript:;" onclick="change_status(this,${row.id},0)" class="btn btn-success">Active</a>`:`<a href="javascript:;" onclick="change_status(this,${row.id},1)" class="btn btn-danger">Deactive</a>`;
        }
    },
    {
        field: "Actions",

        title: "Actions",
        sortable: false,
        overflow: 'visible',
        template: function (row) {


            return '\
            <a href="admin/franchise/'+row.id+'/edit" class="btn btn-warning btn-xs" style="padding:5px;font-size:12px;">\
            edit</i>\
            </a>\
            <a href="admin/franchise_delete_record/'+row.id+'" class="btn btn-danger btn-xs" title="show details" style="padding:5px;font-size:12px;" onclick="delete_record(this); return false;">\
            delete\
            </a>\
            ';
        }
    }
    ]
});

</script>
<script type="text/javascript">

  function change_status(obj,id,activity) {
    console.log(id,activity);
    $.ajax({
        url: "{{ route('franchise-change-status') }}", 
        method:"POST",
        data:{'user_id':id,'activity':activity},
        // dataType:"text",
        success: function(response){
            // console.log(response);return false;
            if(response.activity){
                if(activity)
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',0)" class="btn btn-success"> Active </a>');
                else
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',1)" class="btn btn-danger"> Deactive </a>');

                toastr.success(response.message);
                console.log(activity);
            }else{
             toastr.error(response.message);

         }
     }});

}

</script>



@endpush