routes/web.php
<?php

Route::get('/', 'PublicHomeController@index');
// Route::get('/', function () {
// 	//return Redirect::route('user-register.index');

//    // return view('public.home');
// });


Route::get('/check-me', function(){
	$captains =App\Captain::with('rates')->get();
  //App\Http\Resources\CaptainCollection::withoutWrapping();
	$data=new App\Http\Resources\CaptainCollection($captains);

	return $data;
});

Route::get('/custom_offer' ,'ScheduleController@custom_offer')->name('custom_offer');
Route::get('/weakly_offer' ,'ScheduleController@weakly_offer')->name('weakly_offer');
Route::get('/yearly_offer' ,'ScheduleController@yearly_offer')->name('yearly_offer');
Route::get('/monthly_offer' ,'ScheduleController@monthly_offer')->name('monthly_offer');
//////Admin Routes;
Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	

/////user Dashboard
Route::prefix('user')->group(function(){
 // Authentication Routes...
	Auth::routes();
	Route::get('/profile', 'User\UserResource@profile')->name('user.profile');
	Route::get('/', 'HomeController@index')->name('home');
	Route::get('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::post('/logout', 'Auth\LoginController@logout')->name('user.logout');
	Route::Resource('advance-booking','User\AdvanceBookingController');
	Route::Resource('good','User\GoodsController');
	Route::Resource('vehical','User\VehicalTypeController');
	Route::Resource('booking','User\BookingController');
	Route::Resource('Ride','User\RidesController');
	Route::get('pending-Ridess', 'User\RidesController@pendingride')->name('pending-Rides');
	Route::Resource('googlemap' ,'User\GoogleMapController');
	Route::Resource('userResources' ,'User\UserResource');
	Route::get('user-walletss/{id}', 'User\UserResource@walletShow');
	

});

Route::prefix('admin')->group(function(){

	Route::get('/giveme','Admin\RoleController@giveme');
	Route::get('/checkme','Admin\RoleController@checkme');

	////Accounts
	Route::resource('code','Admin\Account\AccountCodeController');
	Route::resource('bank-deposit','Admin\Account\BankDepositController');
	Route::resource('bank-payment','Admin\Account\BankPaymentController');
	Route::resource('cash-payment','Admin\Account\CashPaymentController');
	Route::resource('cash-reciept','Admin\Account\CashRecieptController');
	Route::resource('invoice','Admin\Account\InvoiceController');
	Route::resource('journal-voucher','Admin\Account\JvController');
	Route::resource('ledger','Admin\Account\LedgerController');
	Route::resource('financials','Admin\Account\FinancialController');
	Route::resource('payable','Admin\Account\PayableAccountController');
	Route::resource('receivable','Admin\Account\RecivableController');
	Route::get('/accounts/detail','Admin\Account\LedgerController@all_account_record')->name('code.all_account');
	Route::post('code/create','Admin\Account\AccountCodeController@create_form')->name('account.new_acc');
Route::post('code/get_account', 'Admin\Account\AccountCodeController@get_account')->name('get_account');
Route::post('recivable/reciveable_account_record','Admin\Account\RecivableController@reciveable_account_record')->name('reciveable_account_record');
Route::post('payable/payables_account_record','Admin\Account\PayableAccountController@payables_account_record')->name('payables_account_record');
Route::post('/ledger/ledger_detail', 'Admin\Account\LedgerController@ledger_detail')->name('ledger_detail');
Route::post('ledger/search/record','Admin\Account\LedgerController@search_ledger_amount')->name('search_ledger_amount');

	Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
	
	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

	Route::get('/', 'AdminController@index')->name('admin.dashboard');
	Route::Resource('userResource' ,'UserResource');

	Route::get('/user/send','UserResource@send');
Route::get('delete_record/{id}' ,'UserResource@delete_record');
	Route::post('/user_data','UserResource@get_users')->name('get-data');
	Route::post('/user_status','UserResource@user_change_status')->name('user-change-status');

	Route::get('/booking-detail/{id}' ,'UserResource@bookingdetail')->name('booking-detail');
	Route::get('user-wallet/{id}', 'UserResource@walletShow')->name('user-wallet');

	Route::Resource('adminResource' ,'AdminResource');

	Route::post('/admin_data','AdminResource@get_admin')->name('get-admin');
	Route::post('/admin_status','AdminResource@admin_change_status')->name('admin-change-status');
Route::get('admin_delete_record/{id}' ,'AdminResource@delete_record');

	Route::Resource('captainResource' ,'CaptainResource');

	Route::post('/captain_account', 'CaptainResource@captain_account')->name('captain_account');

	Route::post('/captain_getsss','CaptainResource@get_captain')->name('get-captainss');
	Route::post('/change_status','CaptainResource@captain_change_status')->name('captain-change-status');
Route::get('captain/delete_record/{id}' ,'CaptainResource@delete_record');
	Route::get('captain-wallet/{id}', 'CaptainResource@walletShow')->name('captain-wallet');


	Route::Resource('goods' ,'GoodsController');
	Route::get('good_delete_record/{id}' ,'GoodsController@delete_record');
	Route::get('good/delete_record/{id}' ,'GoodsController@delete_record');
	Route::post('/get_good','GoodsController@get_good')->name('get-good');
	Route::post('/good_status','GoodsController@good_change_status')->name('good-change-status');

	Route::Resource('captain-wallet' ,'CaptainWalletController');
	Route::Resource('googlemaps' ,'GoogleMapController');
	Route::Resource('vehicals', 'VehicalTypeController');
	Route::get('vehicals/delete_record/{id}' ,'VehicalTypeController@delete_record');
	Route::post('/get_vehical','VehicalTypeController@get_vehical')->name('get_vehical');
	Route::post('/vehical_change_status','VehicalTypeController@vehical_change_status')->name('vehical-change-status');
	

	Route::Resource('bookings', 'BookingController');
	Route::post('/booking_data','BookingController@get_booking')->name('get-booking');

	Route::Resource('pending-booking', 'PendingBookingController');
	Route::post('/pending_booking_data','PendingBookingController@get_pendingbooking')->name('get-pending-booking');



	Route::Resource('advance-bookings', 'AdvanceBookingController');

	Route::Resource('Rides' , 'RidesController');
	Route::post('/ride-data','RidesController@get_ride')->name('get-ride');
	
	Route::get('pending-Rides', 'RidesController@pendingride')->name('pendingRide');
	Route::post('/pending_data','RidesController@get_pending')->name('get-pending');

	Route::post('/upload_document_file','CaptainResource@upload_document_file')->name('upload_document_file');
	Route::post('/remove_document_file','CaptainResource@remove_document_file')->name('remove_document_file');

	Route::get('search','CaptainResource@searchbar')->name('searching');
	Route::Resource('good-categories' , 'GoodCategoriesController');
	Route::post('/get_cat','GoodCategoriesController@get_cat')->name('get_cat');
	Route::post('/cat_status','GoodCategoriesController@categories_change_status')->name('cat-change-status');

	Route::Resource('vehicle-sub-categories' , 'VehicleSubCategoriesController');
	Route::get('vehicle_delete_record/{id}' ,'VehicleSubCategoriesController@delete_record');
	Route::post('/get_sub_vehical','VehicleSubCategoriesController@get_sub_vehical')->name('get_sub_vehical');
	Route::post('/vcategories_change','VehicleSubCategoriesController@vcategories_change_status')->name('vcategories_change_status');
	Route::get('vehicle_categoires', 'VehicleSubCategoriesController@select_vehicle_categories')->name('vehicle-categories_data');

	Route::Resource('vehical-categories' , 'VehicalCategoriesController');
		Route::get('vehicle_categories_delete_record/{id}' ,'VehicalCategoriesController@delete_record');
	Route::post('/get_cat_vehical','VehicalCategoriesController@get_cat_vehical')->name('get-cat-vehical');
	Route::post('/categories_change_status','VehicalCategoriesController@categories_change_status')->name('category-change-status');

	Route::resource('roles', 'RoleController');
	Route::resource('permissions', 'PermissionController');
	Route::resource('financial', 'FinancialController');

	Route::get('report/{id}', 'CaptainReportController@report');
	Route::get('captain_report' ,'CaptainReportController@filtercaptain')->name('captain_report');
	
	Route::resource('report' , 'CaptainReportController');

	Route::get('/get-captains-ajax' ,'CaptainResource@get_captains_ajax');
	Route::resource('inflow' , 'TransactionController' );
	Route::post('/traction','TransactionController@tracking_datas')->name('transaction-history');
	Route::resource('/emergencies','EmergencyController');
	Route::get('emergency_delete_record/{id}' ,'EmergencyController@delete_record');
		Route::post('/get_emergencies','EmergencyController@get_emergnecies')->name('get-emergencies');
		Route::post('/emergencies_change_status','EmergencyController@emergnecies_change_status')->name('emergencies-change-status');


	Route::resource('/offers','OfferController');
	Route::get('offer_delete_record/{id}' ,'OfferController@delete_record');
		Route::post('/get_offer','OfferController@get_offers')->name('get-offer');
		Route::post('/offer_change_status','OfferController@offerschange_status')->name('offer-change-status');

	Route::Resource('skip-reasons' ,'SkipReasonController');

app/Http/Controllers/User/AdvanceBookingController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\AdvanceBooking;
use Illuminate\Support\Facades\Input;

class AdvanceBookingController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {
        $book = AdvanceBooking::orderBy('id', 'DESC')->with("user")->with("vehical")->with("good")->paginate(5);
       
        $books =AdvanceBooking::count();
        return view('user.advanceBooking' , compact([ 'book', 'books']));
    }
}

app/Http/Controllers/User/BookingController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use App\Booking;
use App\Ride;
use Illuminate\Support\Facades\Input;
use Auth;

class BookingController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    public function index()
    {
        $book = Booking::where('user_id', Auth::guard('web')->id())->orderBy('id', 'DESC')->with('BookingDestination')->with('user')->with('good')->paginate(10);
        $books =Booking::count();
        return view('user.bookings' , compact([ 'book', 'books']));
    }

    public function show($id)
    {
        $Booking = Booking::where('id', $id)->with('BookingDestination')->with('good')->with('user')->with('vehical')->get();
        $ride = Ride::where('booking_id' , $id)->with('captain')->with('RideCompleted')->get();
        //return $Booking;exit;
        //dd($ride);exit;
      return view('user.bookingDetail', compact('Booking', 'ride'));
    }
}

app/Http/Controllers/User/GoodsController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Http\Controllers\Controller;
use App\Good;


class GoodsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {
        $datatype = Good::orderBy('id', 'DESC')->paginate(5);
       // $datatypes =goods::count();
       // $categoris =goods_categories::count();
        return view('user.goodstype', compact(['$datatype', 'datatype']));
    }

    
    public function create()
    {
        //
    }

    
    public function store(Request $request)
    {
        Good::create([
            'good_name'          => $request['good_name'],
            'good_category_id'   => $request['good_category_id'],
            ]);
        return redirect('good');
    }

    
    public function show(datatype $datatype)
    {
        //
    }

    
    public function edit($id)
    {
         $Datatypes = Good::find($id);
    
        return view('user.goodstypeEdit', compact('Datatypes'));
        
    }

    
    public function update(Request $request, $id)
    {
        $Datatypes = Good::findOrFail($id);
        $input = $request->all();

        $Datatypes->update($input);
        return redirect()->route('good.index');
    }

   
    public function destroy($id)
    {
       $datatyp = Good::find($id);
    
     
       
        $datatyp->delete();
        return Redirect::route('good.index');
    }    
}

app/Http/Controllers/User/GoogleMapController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GoogleMapController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
    {   
        return view('user.maps_vector');
    }
   
}

app/Http/Controllers/User/RidesController.php
<?php

namespace App\Http\Controllers\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;
use App\Http\Controllers\Controller;
use App\Ride;
use App\RidesCompleted;
use Auth;

class RidesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth:web']);
    }
    
        public function index()
        {
            $ride = Ride::where('user_id' , Auth::guard('web')->id())->where('status', 0 )->with("user")->with("captain")->with("booking")->with('BookingDestination')->with("RideCompleted")->orderBy('id', 'DESC')->paginate(10);
            $rides =Ride::count();
            return view('user.rides' , compact([ 'ride', 'rides']));
        }

        public function pendingride()
        {
        $ride = Ride::where('user_id' , Auth::guard('web')->id())->where('status','<>',0)->with("user")->with("captain")->with("booking")->with("advancebookings")->paginate(10);
        $rides =Ride::count();
        return view('user.pendingrides' , compact([ 'ride', 'rides']));
        }

        public function show($id){
            $ride_complete = RidesCompleted::where('ride_id' ,$id)->with('BookingDestination')->first();
            return view('user.rideproof' , compact([ 'ride_complete']));
        }
}

app/Http/Controllers/User/VehicalTypeController.php
<?php

namespace App\Http\Controllers\User;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;


use App\Vehical;


class VehicalTypeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:web');
    }
    
    public function index()
     { 

        $vehicals = Vehical::orderBy('id', 'DESC')->paginate(5);
        //$vehicals =vehicals::count();
       
        return view('user.vehicaltype', compact(['vehicals']));


     }
    public function create()
    {
        
    }

    
    public function store(Request $request)
    {
        Vehical::create([
            'vehical_name'  => $request['vehical_name'],
            'type_id'       => $request['type_id'],
            ]);
        return redirect('vehical');
    }

    
    public function show(vehicalType $vehicalType)
    {
        //
    }

    
    public function edit($id)
    {

         $vehicl = Vehical::find($id);
        return view( 'user.vehicalsEdit', compact('vehicl'));
       
    }

      
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $vehical = Vehical::findOrFail($id);
        

        $vehical->update($input);
        return redirect()->route('vehical.index');
    }

    
    public function destroy($id)
    {
        $vehical = Vehical::find($id);
    
     
       
        $vehical->delete();
        return Redirect::route('vehical.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
   
}

resources/views/admin/user/page_user_profile.blade.php
<?php
/**
 * Project: loader.
 * User: naveed
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>

@extends('_layouts.admin.app')
@section('content')
<div class="page-content-wrapper">
  <div class="page-content">
    <div class="row">
      <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
          <div class="portlet-title">
            <div class="caption">
              <i class="fa fa-user" style="color: #fff;"></i>
              <span class="caption-subject font-red sbold uppercase"> users Form</span>
            </div>

          </div>
          <div class="row">
            <div class="col-md-12">

              <div class="tab-content">
                <div id="tab_1-1" class="tab-pane active">

                  <form method="POST" action="{{ route('userResource.store') }}" enctype = "multipart/form-data" id="upload_new_form">
                    {{ csrf_field() }}
                    <div class="form-group col-md-6">
                      <label class="control-label">First Name</label>
                      <input name = "fname" type="text" placeholder="John" class="form-control">
                      @if ($errors->has('fname'))
                      <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('fname')}}
                      </div>
                      @endif
                    </div>
                    <div class="form-group col-md-6">
                      <label class="control-label">Last Name</label>
                      <input type="text" name = "lname" placeholder="Doe" class="form-control"> 
                      @if ($errors->has('lname'))
                      <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('lname')}}
                      </div>
                      @endif
                    </div>
                    <div class="form-group col-md-6">
                      <label class="control-label">Email</label>
                      <input name = "email" type="email" class="form-control" placeholder="email"> 
                      @if ($errors->has('email'))
                      <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('email')}}
                      </div>
                      @endif
                    </div>

                    <div class="form-group col-md-6">
                      <label class="control-label">phone</label>
                      <input type="text" name = "phone" placeholder="phone" class="form-control"> 
                      @if ($errors->has('phone'))
                      <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('phone')}}
                      </div>
                      @endif
                    </div>

                    <div class="form-group col-md-6">
                      <label class="control-label">Password</label>
                      <input type="password" class="form-control" name = "password">
                      @if ($errors->has('password'))
                      <div class="alert alert-danger" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">×</span>
                          <span class="sr-only">Close</span>
                        </button>
                        <strong>Warning!</strong> {{$errors->first('password')}}
                      </div>
                      @endif
                    </div>
                    <div class="form-group col-md-6">
                      <label class="control-label">Confirm Password</label>
                      <input name = "password_confirmation" type="password" class="form-control"> 
                        @if ($errors->has('password_confirmation'))
                         <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">×</span>
                              <span class="sr-only">Close</span>
                            </button>
                            <strong>Warning!</strong> {{$errors->first('password_confirmation')}}
                          </div>
                        @endif
                    </div>
                    <div  class="form-group col-md-6">
                      <div class = "col-md-4"  style="margin-left: 5px;">
                        <div class="fileinput fileinput-new" data-provides="fileinput" >
                          <div class="fileinput-new thumbnail" >

                            <img src="{{asset('images/user/profile/no-image.png')}}" id="output_image" style="max-width:250px;>

                          </div>
                          <div class="form-group">
                             <label for="images" class="btn btn-primary"  style="position: relative;top: 020px;left:40px;">Upload Profile</label>
                             <input type="file" id="images" name="images" class="hide" style="opacity: 0;">
                          </div>
                        </div>
                      </div>
                    </div>
                    @if ($errors->has('images'))
                         <div class="col-md-6">
                              <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">×</span>
                              <span class="sr-only">Close</span>
                            </button>
                            <strong>Warning!</strong> {{$errors->first('images')}}
                          </div>
                         </div>
                        @endif
               <div class="row" >
                   <div class="col-md-12 form-actions" style="background-color:unset;border: 0;margin-top: 30px;">
                        <div class="col-md-3">
                          <div class="margiv-top-10 pull-right">
                             <button class="btn green" type = "Submit" name = "submit">Save</button>
                             <button class="btn red" type="reset">Cancel</button>
                          </div>
                        </div>
                      </div>
              </div>
             </form>
           </div>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>
</div>



   <style type="text/css">
   .form-actions {
    padding: 20px 20px;
    margin: 0;
    background-color: #f5f5f5;
    border-top: 1px solid #e7ecf1;
  }

  .thumbnail img {

  </style>


  @endsection
  @stack('post-styles')

  <link href="{{asset('assets/global/css/components-rounded.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />

  <link href="{{asset('assets/global/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" type="text/css" />
  <link href="{{asset('assets/global/plugins/jquery-multi-select/css/multi-select.css')}}" rel="stylesheet" type="text/css" />
  <link href="{{asset('assets/global/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
  <link href="{{asset('assets/global/plugins/select2/css/select2-bootstrap.min.css')}}" rel="stylesheet" type="text/css" />


  @push('post-scripts')



  <script type='text/javascript'>
    function preview_image(event) 
    {
     var reader = new FileReader();
     reader.onload = function()
     {
      var output = document.getElementById('output_image');
      output.src = reader.result;
    }
    reader.readAsDataURL(event.target.files[0]);
  }
</script>



@endpush

resources/views/admin/user/userRosource.blade.php
<?php
/**
 * Project: Loader.
 * User: Shafqat
 * Date: 23/07/2018
 * Time: 7:03 PM
 */
?>

@extends('_layouts.admin.app')
@section('content')
<div class="m-portlet m-portlet--mobile">


   

    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                  User Record 
              </h3>
          </div>
      </div>
  </div>
  @component('_components.alerts-default')
  @endcomponent

  <div class="m-portlet__body">

    <!--begin: Search Form -->
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
        <div class="row align-items-center">
            <div class="col-xl-8 order-2 order-xl-1">
                <div class="form-group m-form__group row align-items-center">
                    <div class="col-md-4">
                        <div class="btn-group">
                            <a href="{{ route('userResource.create')}}" id="sample_editable_1_new" class="btn btn-success" style="position: relative;top: -10px;"> Add New
                            </a>
                        </div>
                    <div class="m-input-icon m-input-icon--left">
                        <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                        <span class="m-input-icon__icon m-input-icon__icon--left">
                            <span>
                                <i class="la la-search"></i>
                            </span>
                        </span>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!--end: Search Form -->

<div class="m_datatable" id="child_data_ajax"></div>
</div>



@endsection

@push('post-scripts')


@if(session('success_message')) 

<script type="text/javascript">
   swal({
      title: "Good job!",
      text: "You record delete sucessfully",
      icon: "success",
      button: "Aww yiss!"
  });
</script>
@endif 

<script type="application/javascript">

    var datatable = $('.m_datatable').mDatatable({
    // datasource definition
    data: {
        type: 'remote',
        source: {
            read: {
                url: BASE_URL+'/admin/user_data'
            }
        },
    pageSize: 10, // display 20 records per page
    saveState: {
        cookie: false,
        webstorage: false
    },
    serverPaging: true,
    serverFiltering: true,
    serverSorting: true
},

    // layout definition
    layout: {
        theme: 'default',
        scroll: false,
        height: null,
        footer: false
    },

    // column sorting
    sortable: true,

    pagination: true,

    detail: false,

    search: {
        input: $('#generalSearch')
    },

    // columns definition
    columns: [ 
    {
        field: "images",
        title: "Images ",
        template:function(row){
            var url = BASE_URL+'/images/user/profile/'+row.images
            return `<img src="${url}" style="height:60px;width:60px;">`;

        }
    // responsive: {hidden: 'md'}

},
{
    field: "id",
    title: "User Name",
    template: function (row) {
        return row.fname+" "+row.lname;
    }
},

{
    field: "email",
    title: "Email ",

},
{
    field: "phone",
    title: "Phone ",
},

{
    field: "status",
    title: "Status",
    template: function (row) {
            // return row.status;
            return row.status?`<a href="javascript:;" onclick="change_status(this,${row.id},0)" class="btn btn-success">Active</a>`:`<a href="javascript:;" onclick="change_status(this,${row.id},1)" class="btn btn-danger">Deactive</a>`;
        }
    },
    {
        field: "Actions",

        title: "Actions",
        sortable: false,
        overflow: 'visible',
        template: function (row) {

            return `
            <a href="admin/userResource/${row.id}/edit" class="btn btn-warning btn-xs" style="padding:5px;font-size:12px;">
            edit</i>
            </a>
            <a href="admin/user-wallet/${row.id}" class="btn btn-info btn-xs" style="padding:5px;font-size:12px;">
            wallet</i>
            </a>
            <a href="admin/delete_record/${row.id}"  class="btn btn-danger btn-xs" title="Delete Rocord" style="padding:5px;font-size:12px;"  onclick="delete_record(this); return false;">
            delete
            </a>
            `;
        }
    }
    ]
});

</script>
<script type="text/javascript">

  function change_status(obj,id,activity) {
    console.log(id,activity);
    $.ajax({
        url: "{{ route('user-change-status') }}", 
        method:"POST",
        data:{'user_id':id,'activity':activity},
        // dataType:"text",
        success: function(response){
            // console.log(response);return false;
            if(response.activity){
                if(activity)
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',0)" class="btn btn-success"> Active </a>');
                else
                    $(obj).replaceWith('<a href="javascript:;" onclick="change_status(this,'+id+',1)" class="btn btn-danger"> Deactive </a>');

                toastr.success(response.message);
                console.log(activity);
            }else{
               toastr.error(response.message);

           }
       }});

}

</script>




@endpush